baseurl = "http://interactivefiction.eu"
languageCode = "en"
title = "Roboman akcióra kész!"
theme = "dream"
[params]
headerTitle = "Szöveges kalandjátékok - Interaktív fikciós játszótér"
author = "Roboman"
description = "Interactive fiction játszótér"
